### ISSUE TITLE
Pls Mahdi an Easy Question about Multiple Pubkeys_to_xpoints Before Converting them ...?

### ISSUE THREAD

**Issue by dragonhlf8** [Mehdi256/Rotor-Cuda#3]
Pls Easy Question about Multiple Pubkeys_to_xpoints Before Converting them ...? : i hope you answer me . .Just for Public-Keys Should i include all the pubkeys in my text file " Pubkeys_in.txt" without ( Prefix 02/03 ) ... or thats only in for single mod ?

**Comment by Mehdi256** [comment]
> Pls Easy Question about Multiple Pubkeys_to_xpoints Before Converting them ...? : i hope you answer me . .Just for Public-Keys Should i include all the pubkeys in my text file " Pubkeys_in.txt" without ( Prefix 02/03 ) ... or thats only in for single mod ?

You don't need to convert public keys to xpoint. A large list of public keys includes compressed & uncompressed address Bitcoin. When u run this list in the program, only public keys related to compressed addresses are displayed. And that means xpoints are just compressed. Like puzzles 1 to 160
