### ISSUE TITLE
hi pls man can you help me on this gpu compiling thing fo Linux ? .

### ISSUE THREAD

**Issue by ibm022023** [Mehdi256/Rotor-Cuda#4]
need you to send me a link of of ./Rotor-Cuda or ./Rotor already compiled for gpu=1 ccap=75 ., so i can start this Rotor-program with Nvidia T4 .... Pls here is the old Keyhunt version that is working / worked for me https://github.com/ibm022023/Keyhunt-Linux

**Comment by ibm022023** [comment]
i mean @Mehdi256 if you use My https://github.com/ibm022023/Keyhunt-Linux in google Colab it Works but for Current Rotor Can't .... Hope you Help me https://github.com/ibm022023/Keyhunt-Linux/blob/18d832af4a9100a075a427879311ec8d98bdbe37/BORROW.jpg

**Comment by dragonhlf8** [comment]
@ibm022023 well i have it for you may try this https://github.com/dragonhlf8/RotorWOW
