### ISSUE TITLE
There is a Problem am Confuse about " Saving Progress " should we use -n 1 for one minute saving or ? 

### ISSUE THREAD

**Issue by dragonhlf8** [Mehdi256/Rotor-Cuda#5]
should we use -n 1 for one minute saving or -n 1 - 256 for bit . collision here ?

**Comment by dragonhlf8** [comment]
@Mehdi256 Pls Answer me

**Comment by ibm022023** [comment]
@dragonhlf8 i thaing the Answer is when you use -n without -r it will work like a timer but if you use -n and -r it will act like that function 1-256 bit
